name: Dev Deployment
on:
  push:
    branches: [ main ]
permissions:
  contents:  read
jobs:
  devpull:
    runs-on: self-hosted
    steps:
      - name: Running Discord Notify
        uses: stegzilla/discord-notify@v4
        with: 
          webhook_url: ${{ DISCORDHOOK }}
          title: New Deployment for Haven Dev
          message: A new commit was detected and is being pushed to the dev server
          colour: a0a0a0
      - name: Checkout Code
        uses: actions/checkout@v4.1.2
      - name: Pull Code
        run: | 
          cd D:\Github\ac_scoreboard
          git config --global --add safe.directory D:/Github/ac_scoreboard
          git pull origin main
      - name: Success Discord Notify
        if: ${{ success() }}
        uses: stegzilla/discord-notify@v4
        with: 
          webhook_url: ${{ DISCORDHOOK }}
          title: Successfully Deployed to Haven Dev
          message: Commit successfully deployed
          colour: 00bf00
      - name: Error Discord Notify
        if: ${{ failure() }}
        uses: stegzilla/discord-notify@v4
        with: 
          webhook_url: ${{ DISCORDHOOK }}
          title: Error Deploying to Haven Dev
          message: Check github actions for details
          colour: bf0000
